# Generated by Django 6.0.5 on 2026-07-06 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basicdjangorevision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeuser',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
