# Generated by Django 6.0.5 on 2026-07-06 17:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basicdjangorevision', '0002_alter_customeuser_mobile_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course', models.CharField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('semester', models.IntegerField()),
                ('std_roll', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('std_no', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('std_email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('std_address', models.TextField(blank=True, null=True)),
                ('std_dob', models.DateField()),
                ('std_image', models.ImageField(blank=True, null=True, upload_to='student/')),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'male'), ('FEMALE', 'female'), ('OTHER', 'other')], max_length=20, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
