# Generated by Django 6.0.3 on 2026-07-10 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basicdjangorevision', '0004_branch_course_student_created_at_student_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
