# Generated by Django 6.0.3 on 2026-07-10 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Basicdjangorevision', '0005_student_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
