# Generated by Django 6.0.4 on 2026-05-07 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studetn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('e_no', models.CharField(blank=True, max_length=12, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='studetn')),
            ],
        ),
    ]
