# Generated by Django 6.0.3 on 2026-04-28 18:17

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=30)),
                ('f_adha', models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^\\d{12}$', 'Aadhar number must be exactly 12 digits.')])),
                ('f_vill', models.CharField(max_length=100)),
                ('f_pin', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'PIN code must be exactly 6 digits.')])),
            ],
        ),
        migrations.CreateModel(
            name='CropSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop_name', models.CharField(choices=[('Sugarcane', 'Ganna (Sugarcane)'), ('Wheat', 'Gehu (Wheat)'), ('Rice', 'Dhan (Rice)'), ('Maize', 'Makka (Maize)'), ('Other', 'Anya (Other)')], max_length=50)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7)),
                ('unit', models.CharField(choices=[('KG', 'Kilogram'), ('QTL', 'Quintal'), ('TON', 'Ton')], default='QTL', max_length=5)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.product')),
            ],
        ),
    ]
