# Generated by Django 6.0.4 on 2026-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('roll', models.CharField(max_length=20, unique=True)),
                ('village', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='studetn/')),
                ('Email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
