# Generated by Django 6.0.4 on 2026-04-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.IntegerField(unique=True)),
                ('course', models.CharField(default='BCA', max_length=50)),
                ('location', models.CharField(default='Meerut', max_length=100)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='students/')),
            ],
        ),
    ]
