# Generated by Django 6.0.5 on 2026-05-14 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=5, max_digits=5)),
                ('image', models.FileField(upload_to='product')),
                ('description', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=5, max_digits=5)),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
