# Generated by Django 6.0.5 on 2026-05-14 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_signup'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='fname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='signup',
            old_name='lname',
            new_name='last_name',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='email',
        ),
    ]
