# Generated by Django 6.0.5 on 2026-05-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_rename_fname_signup_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_list',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
