# Generated by Django 6.0.3 on 2026-05-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudsystem', '0002_student_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='std_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
